server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = /robots.txt {
    try_files /robots.txt =404;
  }

  location = /sitemap.xml {
    try_files /sitemap.xml =404;
  }

  location /fr/ {
    try_files $uri $uri/ /fr/index.html;
  }

  location /en/ {
    try_files $uri $uri/ /en/index.html;
  }
}
