server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location /fr/ {
    try_files $uri $uri/ /fr/index.html;
  }

  location /en/ {
    try_files $uri $uri/ /en/index.html;
  }
}
